Updated the trigger-jenkins-build.yml file to update build number file.
Activity: subbu_project

diff --git a/.github/workflows/trigger-jenkins-build.yml b/.github/workflows/trigger-jenkins-build.yml
--- a/.github/workflows/trigger-jenkins-build.yml
+++ b/.github/workflows/trigger-jenkins-build.yml
@@ -88,10 +88,15 @@ jobs:
           BUILD_NUMBER_FILE=".github/build-number.txt"
           if [ -f "$BUILD_NUMBER_FILE" ]; then
             BUILD_NUMBER=$(cat "$BUILD_NUMBER_FILE")
-            BUILD_NUMBER=&((10#BUILD_NUMBER))
+
+            if ! [[ "$BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
+              echo "Error: Build Number is not a valid number. Exiting."
+              exit 1
+            fi
           else
             BUILD_NUMBER= 0
           fi
+
           # Increment Build Number
           BUILD_NUMBER=%((BUILD_NUMBER+1))
 
