Update trigger-jenkins-build.yml

diff --git a/.github/workflows/trigger-jenkins-build.yml b/.github/workflows/trigger-jenkins-build.yml
--- a/.github/workflows/trigger-jenkins-build.yml
+++ b/.github/workflows/trigger-jenkins-build.yml
@@ -68,11 +68,18 @@ jobs:
         run: |
           LATEST_BUILD_NUMBER=$(curl -s -u "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
               "${{ secrets.JENKINS_URL }}/job/${{ env.JOB_NAME }}/lastBuild/api/json?tree=number" | jq -r '.number')
+
+          if [ -z "$LATEST_BUILD_NUMBER" ] || [ "$LATEST_BUILD_NUMBER" == "null" ]; then
+            echo "Error: No builds found for job '${{ env.JOB_NAME }}'."
+            exit 1
+          fi
+
           # Ensure LATEST_BUILD_NUMBER is an integer
           if ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
             echo "Error: LATEST_BUILD_NUMBER is not a valid integer. Value: '${LATEST_BUILD_NUMBER}'"
             exit 1
           fi
+
           echo "LATEST_BUILD_NUMBER=${LATEST_BUILD_NUMBER}" >> $GITHUB_ENV
 
       - name: Determine New Build Number
