Updated the trigger-jenkins-build.yml file.
Activity: subbu_project

diff --git a/.github/workflows/trigger-jenkins-build.yml b/.github/workflows/trigger-jenkins-build.yml
--- a/.github/workflows/trigger-jenkins-build.yml
+++ b/.github/workflows/trigger-jenkins-build.yml
@@ -12,6 +12,8 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+        with:
+          persist-credentials: false # to avoid issues with using personal tokens
 
       - name: Get Commit Message
         id: get-commit-message
@@ -164,13 +166,13 @@ jobs:
           git config user.name "github-actions"
           git config user.email "actions@github.com"
 
-          git fetch || { echo "git fetch failed"; exit 1; }
+          git fetch origin || { echo "git fetch failed"; exit 1; }
           git reset --hard origin/${GITHUB_REF#refs/heads/} || { echo "git reset failed"; exit 1; }
 
           git add "$OLD_BUILD_NUMBER_FILE" "$NEW_BUILD_NUMBER_FILE"
           if ! git diff --cached --quiet; then
             git commit -m "Update old build number to ${{ env.LATEST_BUILD_NUMBER }} and append new build numbers with statuses" || { echo "git commit failed"; exit 1; }
-            git push || { echo "git push failed"; exit 1; }
+            git push origin HEAD:${GITHUB_REF#refs/heads/} || { echo "git push failed"; exit 1; }
           else
             echo "No changes to commit"
           fi
