Updated the .yml and build_number files.
Activity: subbu_project

diff --git a/.github/workflows/trigger-jenkins-build.yml b/.github/workflows/trigger-jenkins-build.yml
--- a/.github/workflows/trigger-jenkins-build.yml
+++ b/.github/workflows/trigger-jenkins-build.yml
@@ -138,23 +138,27 @@ jobs:
         if: steps.trigger-build.outcome == 'success'
         id: update-build-number
         run: |
-          BUILD_NUMBER_FILE="/home/subbaramaiah_ch/subbu/subbu_project/new_build_number.txt"
+         OLD_BUILD_NUMBER_FILE="/home/subbaramaiah_ch/subbu/subbu_project/old_build_number.txt"
+         NEW_BUILD_NUMBER_FILE="/home/subbaramaiah_ch/subbu/subbu_project/new_build_number.txt"
 
-          # Update build number in the file
-          echo "${{ env.LATEST_BUILD_NUMBER }}" >> "$BUILD_NUMBER_FILE"
+         # Updating the old build number into "old_build_number.txt"
+         echo "${{ env.LOCAL_BUILD_NUMBER }}" > "$OLD_BUILD_NUMBER_FILE"
+         echo "Updating the Old Build Number with ${{ env.LOCAL_BUILD_NUMBER }} to $OLD_BUILD_NUMBER_FILE" 
+         # Updating the new build number into "new_build_number.txt"
+         echo "${{ env.LATEST_BUILD_NUMBER }}" >> "$NEW_BUILD_NUMBER_FILE"
+         echo "Updating the Latest Build Number with ${{env.LATEST_BUILD_NUMBER}} to $NEW_BUILD_NUMBER_FILE"
 
-          echo "Updating the Latest Build Number with ${{env.LATEST_BUILD_NUMBER}} to $BUILD_NUMBER_FILE"
-          # Configure Git and commit the updated build number
-          git config user.name "github-actions"
-          git config user.email "actions@github.com"
+         # Configure Git and commit the updated build number
+         git config user.name "github-actions"
+         git config user.email "actions@github.com"
 
-          git fetch || { echo "git fetch failed"; exit 1; }
-          git reset --hard origin/${GITHUB_REF#refs/heads/} || { echo "git reset failed"; exit 1; }
+         git fetch || { echo "git fetch failed"; exit 1; }
+         git reset --hard origin/${GITHUB_REF#refs/heads/} || { echo "git reset failed"; exit 1; }
 
-          git add "$BUILD_NUMBER_FILE"
-          if ! git diff --cached --quiet; then
-            git commit -m "Update build number to ${{ env.LATEST_BUILD_NUMBER }}" || { echo "git commit failed"; exit 1; }
-            git push || { echo "git push failed"; exit 1; }
-          else
-            echo "No changes to commit"
-          fi
+         git add "$BUILD_NUMBER_FILE"
+         if ! git diff --cached --quiet; then
+           git commit -m "Update build number to ${{ env.LATEST_BUILD_NUMBER }}" || { echo "git commit failed"; exit 1; }
+           git push || { echo "git push failed"; exit 1; }
+         else
+           echo "No changes to commit"
+         fi
